version: '3.7'

services:
  web:
    image: sua_imagem
    deploy:
      replicas: 5
      endpoint_mode: vip
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.http.services.web-app.loadbalancer.server.port=8000"
      resources:
        reservations:
          cpus: '0.1'
          memory: 50M
    ports:
      - "8000:8000"
    networks:
      - minha_rede
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 50M
    environment:
      - SWARM_MODE=1
    configs:
      - source: my_config
        target: /app/config.txt
      - source: my_secret
        target: /app/secret.txt

networks:
  minha_rede:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
